package com.clinicaxz.enums;

public enum EnumFuncionalidades {
    // Funcionalidades da Secretária
    CADASTRAR_MEDICO,
    EDITAR_MEDICO,
    INATIVAR_MEDICO,
    LISTAR_MEDICOS,
    
    CADASTRAR_PACIENTE,
    EDITAR_PACIENTE,
    INATIVAR_PACIENTE,
    LISTAR_PACIENTES,
    
    CADASTRAR_CONVENIO,
    EDITAR_CONVENIO,
    INATIVAR_CONVENIO,
    LISTAR_CONVENIOS,
    
    CADASTRAR_ESPECIALIDADE,
    EDITAR_ESPECIALIDADE,
    INATIVAR_ESPECIALIDADE,
    LISTAR_ESPECIALIDADES,
    
    AGENDAR_CONSULTA,
    REMARCAR_CONSULTA,
    CANCELAR_CONSULTA,
    VISUALIZAR_AGENDA_COMPLETA,
    
    // Funcionalidades do Médico
    VISUALIZAR_AGENDA_PROPRIA,
    REALIZAR_ATENDIMENTO,
    REGISTRAR_PRONTUARIO,
    CONSULTAR_HISTORICO_PACIENTE,
    
    // Funcionalidades Administrativas
    GERENCIAR_USUARIOS,
    GERENCIAR_PERFIS
}
